### ISSUE TITLE
[question] Flexible HUD pk3 placed into base folder, but no additional commands recognized? 

### ISSUE THREAD

**Issue by r3538987** [zturtleman/ioq3#10]
Hello, 
Maybe there will be someone who can assist and point out what pieces I'm missing.
- ztm-flexible-hud-r7-baseq3.pk3 inserted into base and missionpack folders
- had vm folders in these, so as suggested both were renamed into vm-ioq3
- ioquake executable I have is from ioq3 - 2021.03.17
But still game in console dont recognize new commands like /cg_stretch. 

Other pk3 files loads just fine. FlexibeHUD seems refuse to load, with others or even if left alone. 

Folder structure.
[https://i.imgur.com/bF3U4RQ.png](https://i.imgur.com/bF3U4RQ.png)

**Comment by r3538987** [comment]
Found this topic - https://discourse.ioquake.org/t/flexible-hud-mod-for-ioq3/1012/19
But still no luck.

So far I can make it work with quake3e build from 13.09.2023. 
Saw an comments that people reported pk3 is incompatible with some older versions, so maybe I'm lucky and got that combo.

**Comment by zturtleman** [comment]
Start a single player / skirmish game and open the console and ensure `vm_cgame` cvar is 2 and run `which vm/cgame.qvm` to see if the hud is loaded from flexible hud mod or another pk3.

**Comment by r3538987** [comment]
Thanks, vm_cgame was set to 0, after setting to 2, and restarting level HUD appeared non-stretched.
