### ISSUE TITLE
Not really so much of an issue as a question.

### ISSUE THREAD

**Issue by Kr3m** [zturtleman/ioq3#9]
I was debating integrating your flexible-hud code into a mod of mine, but this mod is based on Cyrax's baseq3a which doesn't seem to suffer from some of the stretching issues and seems pretty decent.  I'm wondering what if anything should be added from flexible-hud, and if there are differences, should flexible-hud code take priority over baseq3a code or vice versa?

I apologize in advance if this is not the proper place to ask this question and again if you have no knowledge of baseq3a code.

**Comment by zturtleman** [comment]
Hello. I don't have knowledge of the baseq3a code. baseq3a is under the Q3 SDK license which is incompatible with the GPL license used by my flexible hud mod and ioq3 which I used as a base.
